openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.0.0
  description: RESTful API for authentication and authorization

paths:
  /auth/login:
    post:
      summary: User login
      description: Authenticate user and return JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                    default: bearer
        '401':
          description: Invalid credentials

  /auth/validate:
    get:
      summary: Validate JWT token
      description: Verify token validity and return user information
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  customer_id:
                    type: string
                  role:
                    type: string
        '401':
          description: Invalid or expired token

  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
