openapi: 3.0.0
info:
  title: Customer Service API
  version: 1.0.0
  description: RESTful API for managing customer information

paths:
  /customers/{id}:
    get:
      summary: Get customer information
      description: Retrieve detailed information about a specific customer
      parameters:
        - name: id
          in: path
          required: true
          description: Customer ID
          schema:
            type: string
      responses:
        '200':
          description: Customer information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found

  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string
